### PR TITLE
Add junit 4 assertion quick fixes

### LINKED ISSUE #12: Add quick fixes for junit assertion replacements
Methods like `assertEquals` and `fail` have corresponding methods in assertk that should be straightforward to replace

### PR DESCRIPTION
**Pull request by jzbrooks**
Fixes #12

### CODE REVIEW

File: checks/src/main/kotlin/com/jzbrooks/assertk/lint/checks/TestFrameworkAssertionDetector.kt [hunk 1]
```diff
@@ -22,34 +24,180 @@ class TestFrameworkAssertionDetector :
...
+
+                            if (call.valueArguments.size == 3) {
+                                append(" // ")
+                                append(
+                                    call.valueArguments
+                                        .first()
+                                        .sourcePsi!!
+                                        .text,
+                                )
+                            }
```
Comment (jzbrooks) [inline checks/src/main/kotlin/com/jzbrooks/assertk/lint/checks/TestFrameworkAssertionDetector.kt:158]: It could be worth offering this in a variation in case people don't really care to keep the message. Sometimes those messages carry useful context.

If assertk implements https://github.com/willowtreeapps/assertk/issues/534, then a variation based on that API would probably be useful.

For now, comments don't hurt and this approach errs on the side of not destroying information.
